# Ensure the platform is set to iOS 12.0 or higher
platform :ios, '12.0'

# CocoaPods analytics sends network stats to help improve the tool.
# Without this, it might hang in CI environments.
install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',
        
        ## dart: [PermissionGroup.notifications]
        # 'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end
